// import { Inter } from 'next/font/google'
import './globals.css'
import GoogleAnalytics from './GoogleAnalytics';

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Decisive Development',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body >
                <GoogleAnalytics />
                {children}            
            </body>
        </html>
    )
}
