import './globals.css'
import { GoogleAnalytics } from '@next/third-parties/google'

export const metadata = {
    title: 'Decisive Development',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <GoogleAnalytics gaId="G-4F8JF72NNQ" />
            <body >
                {children}            
            </body>
        </html>
    )
}
